applogpath: $GOPATH/src/coralreefci/data/backtests/application-%Y%m%d%H%M.log
modellogpath: $GOPATH/src/coralreefci/data/backtests/model-%Y%m%d%H%M.log
datacachespath: $GOPATH/src/coralreefci/data/caches
