applogpath: $GOPATH/src/core/data/logs/application-frontend-%Y%m%d%H%M.log
modellogpath: $GOPATH/src/core/data/logs/model-frontend-%Y%m%d%H%M.log
datacachespath: $GOPATH/src/core/data/caches
boltdbpath: $GOPATH/src/core/data/bolt/storage.db
activationserveraddress: "127.0.0.1:8010"
activationserviceendpoint: "http://127.0.0.1:8010/activate-service"
ingestorserveraddress: "127.0.0.1:8020"
ingestoractivationendpoint: "http://127.0.0.1:8020/activate-ingestor-backend"
backendserveraddress: "127.0.0.1:8030"
backendactivationendpoint: "http://127.0.0.1:8030/activate-ingestor-backend"
