applogpath: $GOPATH/src/core/data/logs/application-frontend-%Y%m%d%H%M.log
modellogpath: $GOPATH/src/core/data/logs/model-frontend-%Y%m%d%H%M.log
datacachespath: $GOPATH/src/core/data/caches
ingestorgobs: $GOPATH/src/core/data/ingestorgobs
activationserveraddress: "10.142.1.0:8010"
activationserviceendpoint: "http://10.142.1.0:8010/activate-service"
ingestorserveraddress: "10.142.1.0:8020"
ingestoractivationendpoint: "http://10.142.1.0:8020/activate-ingestor-backend"
backendserveraddress: "10.142.1.0:8030"
backendactivationendpoint: "http://10.142.1.0:8030/activate-ingestor-backend"
