applogpath: $GOPATH/src/core/data/logs/application-ingestor-%Y%m%d%H%M.log
modellogpath: $GOPATH/src/core/data/logs/model-ingestor-%Y%m%d%H%M.log
datacachespath: $GOPATH/src/core/data/caches
boltdbpath: $GOPATH/src/core/data/bolt/storage.db
activationserviceendpoint: "http://10.142.1.0:8010/activate-service"
